# rendered by https://www.npmjs.com/package/github-actions-checks
name: Check PR
on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run checks
        uses: sendsay-ru/.github/.github/workflows/lint.yml
        with:
          config-path: .github/lint.json
        secrets: inherit
